version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
      - USER=transmission
      - PASS=transmission #NEED TO CHANGE THIS
    volumes:
      - /home/ubuntu/docker_compose/transmission:/config
      - /mnt/onedrive/downloads:/downloads
      - /mnt/onedrive/downloads/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  transmission-mam:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission-mam
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
      - USER=transmission
      - PASS=transmission #NEED TO CHANGE THIS
    volumes:
      - /home/ubuntu/docker_compose/transmission_mam:/config
      - /mnt/onedrive/downloads/books:/downloads
      - /mnt/onedrive/downloads/watch:/watch
    ports:
      - 9092:9091
      - 51414:51413
      - 51414:51413/udp
    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - /home/ubuntu/docker_compose/readarr:/config
      - /mnt/onedrive/books:/books
      - /mnt/onedrive/downloads/books/complete:/downloads/complete
    ports:
      - 8787:8787
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - /home/ubuntu/docker_compose/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - /home/ubuntu/docker_compose/calibre:/config
    ports:
      - 8080:8080
      - 8181:8181
      - 8081:8081
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /home/ubuntu/docker_compose/plex:/config
      - /mnt/onedrive/series:/tv
      - /mnt/onedrive/downloads/complete:/movies
      - /dev/shm:/transcode
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
    volumes:
      - /home/ubuntu/docker_compose/sonarr:/config
      - /mnt/onedrive/series:/tv #optional
      - /mnt/onedrive/downloads/complete:/downloads/complete #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /home/ubuntu/docker_compose/jellyfin:/config
      - /mnt/onedrive/series:/data/tvshows
      - /mnt/onedrive/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
volumes:
  transcode:
    external: true
