version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
      - USER=transmission
      - PASS=transmission #NEED TO CHANGE THIS
    volumes:
      - /transmission/config:/config
      - /mnt/onedrive/downloads:/downloads
      - /mnt/onedrive/downloads/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${GUID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /plex/config:/config
      - /mnt/onedrive/downloads/complete:/tv
      - /mnt/onedrive/downloads/complete:/movies
      - /dev/shm:/transcode
    restart: unless-stopped

volumes:
  transcode:
    external: true